language: python

python:
  - 2.6
  - 2.7

env:
  - DJANGO_VERSION=1.5c1
  - DJANGO_VERSION=1.4.3

install:
  - pip install -q Django==$DJANGO_VERSION --use-mirrors
  - pip install flake8 --use-mirrors
  - pip install -q -r requirements.txt --use-mirrors
  - pip install -e . --use-mirrors

script:
  - flake8 --max-line-length=100 .
  - python setup.py test
